### ISSUE TITLE
UP 主小姐姐，我又来提问啦～ 在每次更新博客 build 了之后，传到服务器的文件是如何更新的？因为我的是放在 nginx 下的。每次更新都得删掉之前的文件，这样挺麻烦的。想请教一下你是如何处理的？

### ISSUE THREAD

**Issue by weissleeC** [uniquemo/gatsby-blog#9]
https://github.com/uniquemo/gatsby-blog/blob/c851b4ebf42dff76021c88f9991b923ef3eaa150/package.json#L63

**Comment by uniquemo** [comment]
这个不需要删掉喔，因为生成的文件都是带有哈希的 @weissleeC
